


package fr.PongEvolution.BoulesEnergie;



///POUR SAVOIR DANS QUELLE DIRECTION VA UNE BOULE D'ENERGIE
public enum Enum_DirectionBouleEnergie {
	DIRECTION_BOULE_ENERGIE_GAUCHE_TOUT_DROIT,
	DIRECTION_BOULE_ENERGIE_GAUCHE_HAUT,
	DIRECTION_BOULE_ENERGIE_GAUCHE_BAS,
	DIRECTION_BOULE_ENERGIE_DROITE_TOUT_DROIT,
	DIRECTION_BOULE_ENERGIE_DROITE_HAUT,
	DIRECTION_BOULE_ENERGIE_DROITE_BAS;
}



